### ISSUE TITLE
videograbber: check if there is a way to reset usb connected card

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#121]
so we could e.g. do it nightly or whenever there is some unexpected period of inactivity (e.g. at night... should not hurt)

**Comment by vmdocua** [comment]
Did small **research** and comments listed below:

1. There is no API to reboot Magewell USB Capture device directly in SDK.
2. Didn't find the same functionality in Magewell usbcapture utility UI provided with device.
3. Tested 1st attemp to reboot device in Linux with `lsusb`/`usbreset` and it failed (but actually I believe should exist some command to do this).

**Note:** In future we can add some keyboard shortcut to force internal utilty restart, like it does when config file changed in runtime. But initially we need in test for this approach, so we can just touch config file in this case and see if capture process is restored in this case. In case it will recovery everything, we can integrate this logic directly into `reprostim-videocapture` so it autorestart internal engine case of 'no-videos' for some long time.
