### ISSUE TITLE
Setup audio capture

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#15]
The [card](https://www.amazon.com/gp/product/B01MSDFAO5/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) allows for audio capture :

 - Audio Input: HDMI Embedded and Analog via 3.5mm Line-in

so we should route audio delivered to scanner system there as well

**Comment by andycon** [comment]
We are waiting for audio splitter. It was ordered from amazon last week.

**Comment by andycon** [comment]
I have been working to set up the new audio cables. Of course, this is not just plug and play, so I need to configure the audio-capture to read from the analog input. In researching this, I found that there is a new Magewell SDK update from last fall. This has its own mp4 recording library, plus new Python bindings to all functionality.  I plan to convert all Reprostim capture to python code, from the current C++.  Also, this code will (hopefully) obviate the need to invoke ffmpeg or any another video recording software.

**Comment by yarikoptic** [comment]
to discover (possibly) which device file audacity uses, just us `lsof -p <PID>` or just `ls -l /proc/<PID/>fd`

**Comment by yarikoptic** [comment]
also checkout google hits on ffmpeg record audio video, which would point to posts like this: https://stackoverflow.com/questions/6311560/how-can-i-capture-audio-and-video-simultenaous-with-ffmpeg-from-a-linux-usb-capt
