### ISSUE TITLE
usb sniffer to connect to lumina usb output to sniff subject responses and MRI triggers

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#19]
may be smth like https://www.bugblat.com/products/minisniff/ ?

must be transparent to the "user"

**Comment by andycon** [comment]
tried mini sniffer. Minisniffer requires explicit setting for pass-thru mode. Not easily deployable without adding weak/unreliable link in critical point. Could disrupt normal response collection / trigger collection during routine scanning operations.

**Comment by andycon** [comment]
Superseded by #35
