### ISSUE TITLE
Make VideoCapture auto-detect resolution changes again

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#60]
It used to work and was deployed. When I tried to move to the new capturing "server" (databeast) it seemed like the script no longer discovered the Magewell device correctly on it to be able to detect resolution changes.  That should be done [here](https://github.com/ReproNim/reprostim/blob/master/Capture/C%2B%2B/VideoCapture.cpp#L294) . I just now realized (with a reminder from @vmdocua that utility needed sudo) that it must be permission issue: we need to make sure that the user who runs the utility is part of the group which has access to those usb devices.  Most likely it should be a "plugdev" group.  

IIRC  original box we had some  udev setup file to assign to a desired group...

So part of this issue is likely to just setup the /etc/udev/rules.d/reprostim.rules file which would give proper ownership. 

@yarikoptic also check the file on old box and test locally.

**Comment by vmdocua** [comment]
Provided information how to configure udev for Magewell USB device in readme docs, utility updated to provide better information and diagnostics in console output about similar problems for future.
