### ISSUE TITLE
Setup automated figuring out of audio device

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#66]
- as associated with the USB device of video capture
- prior issue https://github.com/ReproNim/reprostim/issues/15 has some pointers which might be of help

**Comment by yarikoptic** [comment]
this is done already right @vmdocua ?

**Comment by vmdocua** [comment]
As was discussed and tested before, current code detect automatically audio device based on Magewell capture device serial number and select hardcoded HDMI:0 (after recent changes Line-In:1) sub-device. Capture device can have multiple audio-in sub-devices, e.g. HDMI audio, Line-In audio etc and probably this selection is done on hardware level by user where real cable connected and used. 

Current plan to improve and fix the issue:

A) Extend  [a_dev: "auto"] option in config.yaml with syntax like "auto,321", so it will be expanded to "-i hw:<detected_card_id>,321".

B) Provide in configuration ability to specify default audio sub-device in human readable terms, like "HDMI", "Line-In" etc. and try to match it in runtime with ALSA and brothers. Add notes in documentation for end-user regarding this option.

**Comment by vmdocua** [comment]
Just to summarize current issue state, `"a_dev"` options can be specified  with options listed below. Note that they are listed in execution priority descending order:

1. Specify "a_dev" explicitly in ALSA format with sound card and device IDs (hw:<sound_card_id>,<device_id>):

    `a_dev: "-i hw:2,0"`

    `a_dev: "hw:2,0"`

1. Specify only device ID explicitly. In this case sound card ID will be automatically calculated by target capture USB device:

	`a_dev: "auto,2"`

1. Specify that both sound card ID and capture device ID are calculated automatically. This is recommended value to use and default configuration option:

	`a_dev: "auto"`

1. When code fails to calculate device ID it will fallback to default hardcoded value listed in capture lib:

	`#define DEFAULT_AUDIO_IN_DEVICE "1"`
