### ISSUE TITLE
Make it possible to reload configuration if config file changes

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#69]
while dealing with "deployed" solution, trying to avoid interference with already ongoing data collection, it would be great if we could make it to reload config file to e.g. discover / use adjusted ffmpeg options.  I guess one way could be just to make it react to some signal (HUP) and do reload of config then. Another, to monitor config file (remember mtime upon read, check mtime later if changes -- reload).

**Comment by vmdocua** [comment]
Implemented in PR #71
