### ISSUE TITLE
do not record "no signal" screen

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#82]
as we discovered yesterday, `reprostim-videocapture` was recording the "No signal" video

![image](https://github.com/ReproNim/reprostim/assets/39889/88087b58-4770-4cbd-8cbe-fbf23a286307)

nothing was plugged in to that VGA cable.  Then I connected the USB->VGA to my laptop and script detected new recording and restarted ffmpeg. After I disconnected it just said that resolution is whacky and didn't start ffmpeg.

So I think the card some times might get some stale state where it would think that something is connected whenever it is not.  May be we could rule it out based on resolution/sampling rate?

here is a sample video: http://www.oneukrainian.com/tmp/2024.03.18.14.44.04.848_.mkv

**Comment by yarikoptic** [comment]
would be great to get a script which is given a video file, it would tell how many periods of "no signal" in it and what % of total video duration it is .

**Comment by yarikoptic** [comment]
I think it is again due to some "whacky resolution"... we need to figure out reliable way to detect such condition!

**Comment by yarikoptic** [comment]
options: given a single file -- give information about it. May be exit with code 1 if detect having this "no signal" screen for any duration.

**Comment by vmdocua** [comment]
Just for information, @typhon we scanned videos recorded during year 2024 [2024-01-01..2024-06-11], and placed result logs under "/data/repronim/reprostim-reproiner-nosignal-videos/round3_2024_06_11" location. We used 100 frames check for each file, fixed truncated and invalid duration mkv files in tmp location for analysis, and used 50% nosignal frames threshold. Good thing is that in May and June 2024 we don't see videos containing many nosignal frames.

**Comment by yarikoptic** [comment]
```
yoh@typhon:~$ grep NOSIGNAL_COUNT  /data/repronim/reprostim-reproiner-nosignal-videos/round3_2024_06_11/*
/data/repronim/reprostim-reproiner-nosignal-videos/round3_2024_06_11/ns_20240611_110126.log:NOSIGNAL_COUNT : 0
/data/repronim/reprostim-reproiner-nosignal-videos/round3_2024_06_11/ns_20240611_110332.log:NOSIGNAL_COUNT : 0
/data/repronim/reprostim-reproiner-nosignal-videos/round3_2024_06_11/ns_20240611_111725.log:NOSIGNAL_COUNT : 22
/data/repronim/reprostim-reproiner-nosignal-videos/round3_2024_06_11/ns_20240611_120924.log:NOSIGNAL_COUNT : 16
/data/repronim/reprostim-reproiner-nosignal-videos/round3_2024_06_11/ns_20240611_124422.log:NOSIGNAL_COUNT : 30
/data/repronim/reprostim-reproiner-nosignal-videos/round3_2024_06_11/ns_20240611_133020.log:NOSIGNAL_COUNT : 0
```
